"""replays table

Revision ID: 0d5783098a64
Revises: 5e7d5ee714a9
Create Date: 2026-07-06 01:55:14.431444

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0d5783098a64'
down_revision: str | None = '5e7d5ee714a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replays',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('player_username', sa.String(length=64), nullable=False),
    sa.Column('uploader', sa.String(length=64), nullable=False),
    sa.Column('gamemode', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('bagtype', sa.String(length=32), nullable=True),
    sa.Column('frames', sa.Integer(), nullable=False),
    sa.Column('pps', sa.Float(), nullable=True),
    sa.Column('apm', sa.Float(), nullable=True),
    sa.Column('vsscore', sa.Float(), nullable=True),
    sa.Column('piece_count', sa.Integer(), nullable=True),
    sa.Column('reconstructable', sa.Boolean(), nullable=False),
    sa.Column('reconstructable_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replays'))
    )
    op.create_index(op.f('ix_replays_player_username'), 'replays', ['player_username'], unique=False)
    op.create_index(op.f('ix_replays_sha256'), 'replays', ['sha256'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replays_sha256'), table_name='replays')
    op.drop_index(op.f('ix_replays_player_username'), table_name='replays')
    op.drop_table('replays')
    # ### end Alembic commands ###
