"""smoke table

Revision ID: 5e7d5ee714a9
Revises: 
Create Date: 2026-07-05 09:50:17.081777

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5e7d5ee714a9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smoke_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smoke_notes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smoke_notes')
    # ### end Alembic commands ###
