"""catalog tables

Revision ID: ef39fcdfddfa
Revises: 0d5783098a64
Create Date: 2026-07-06 02:05:44.824719

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ef39fcdfddfa'
down_revision: str | None = '0d5783098a64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.CheckConstraint("category IN ('opener', 'skill')", name=op.f('ck_tags_category_known')),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_tags'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('discord_id', name=op.f('uq_users_discord_id'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('replay_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('start_piece', sa.Integer(), nullable=False),
    sa.Column('end_piece', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=128), nullable=True),
    sa.Column('ups', sa.Integer(), nullable=False),
    sa.Column('downs', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'published', 'removed')", name=op.f('ck_segments_status_known')),
    sa.CheckConstraint('difficulty IS NULL OR (difficulty >= 1 AND difficulty <= 5)', name=op.f('ck_segments_difficulty_range')),
    sa.CheckConstraint('end_piece >= start_piece', name=op.f('ck_segments_window_ordered')),
    sa.CheckConstraint('start_piece >= 0', name=op.f('ck_segments_start_nonneg')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_segments_author_id_users')),
    sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], name=op.f('fk_segments_replay_id_replays')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments'))
    )
    op.create_index(op.f('ix_segments_created_at'), 'segments', ['created_at'], unique=False)
    op.create_index(op.f('ix_segments_replay_id'), 'segments', ['replay_id'], unique=False)
    op.create_index(op.f('ix_segments_score'), 'segments', ['score'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users')),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_reports_segment_id_segments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_segment_id'), 'reports', ['segment_id'], unique=False)
    op.create_table('segment_tags',
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('tag_slug', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_segment_tags_segment_id_segments')),
    sa.ForeignKeyConstraint(['tag_slug'], ['tags.slug'], name=op.f('fk_segment_tags_tag_slug_tags')),
    sa.PrimaryKeyConstraint('segment_id', 'tag_slug', name=op.f('pk_segment_tags'))
    )
    op.create_index(op.f('ix_segment_tags_tag_slug'), 'segment_tags', ['tag_slug'], unique=False)
    op.create_table('votes',
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name=op.f('ck_votes_value_updown')),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_votes_segment_id_segments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_votes_user_id_users')),
    sa.PrimaryKeyConstraint('segment_id', 'user_id', name=op.f('pk_votes'))
    )
    # Hand-adjusted from autogen: sha256 -> file_hash is a RENAME (autogen
    # emitted add-NOT-NULL + drop, which fails on populated tables and loses
    # data). The uploader string column is superseded by uploader_id (its
    # free-text values are deliberately discarded).
    op.add_column('replays', sa.Column('player_userid', sa.String(length=64), nullable=True))
    op.add_column('replays', sa.Column('uploader_id', sa.String(length=36), nullable=True))
    op.add_column('replays', sa.Column('style', sa.String(length=32), nullable=True))
    op.drop_index(op.f('ix_replays_sha256'), table_name='replays')
    op.alter_column('replays', 'sha256', new_column_name='file_hash')
    op.create_index(op.f('ix_replays_file_hash'), 'replays', ['file_hash'], unique=True)
    op.create_index(op.f('ix_replays_gamemode'), 'replays', ['gamemode'], unique=False)
    op.create_index(op.f('ix_replays_style'), 'replays', ['style'], unique=False)
    op.create_foreign_key(op.f('fk_replays_uploader_id_users'), 'replays', 'users', ['uploader_id'], ['id'])
    op.drop_column('replays', 'uploader')

    # Seed the controlled tag vocabulary.
    tags = sa.table(
        'tags',
        sa.column('slug', sa.String),
        sa.column('label', sa.String),
        sa.column('category', sa.String),
    )
    op.bulk_insert(
        tags,
        [
            {'slug': 'tki', 'label': 'TKI', 'category': 'opener'},
            {'slug': 'dt-cannon', 'label': 'DT-cannon', 'category': 'opener'},
            {'slug': 'mko', 'label': 'MKO', 'category': 'opener'},
            {'slug': 'downstack', 'label': 'Downstack', 'category': 'skill'},
            {'slug': 'clean-4wide', 'label': 'Clean 4-wide', 'category': 'skill'},
            {'slug': 'all-spin', 'label': 'All-spin', 'category': 'skill'},
            {'slug': 'burst', 'label': 'Burst', 'category': 'skill'},
            {'slug': 'cheese-clear', 'label': 'Cheese clear', 'category': 'skill'},
            {'slug': 'pc-setup', 'label': 'PC setup', 'category': 'skill'},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replays', sa.Column('uploader', sa.VARCHAR(length=64), autoincrement=False, nullable=False, server_default='anonymous'))
    op.drop_constraint(op.f('fk_replays_uploader_id_users'), 'replays', type_='foreignkey')
    op.drop_index(op.f('ix_replays_style'), table_name='replays')
    op.drop_index(op.f('ix_replays_gamemode'), table_name='replays')
    op.drop_index(op.f('ix_replays_file_hash'), table_name='replays')
    op.alter_column('replays', 'file_hash', new_column_name='sha256')
    op.create_index(op.f('ix_replays_sha256'), 'replays', ['sha256'], unique=True)
    op.drop_column('replays', 'style')
    op.drop_column('replays', 'uploader_id')
    op.drop_column('replays', 'player_userid')
    op.drop_table('votes')
    op.drop_index(op.f('ix_segment_tags_tag_slug'), table_name='segment_tags')
    op.drop_table('segment_tags')
    op.drop_index(op.f('ix_reports_segment_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_segments_score'), table_name='segments')
    op.drop_index(op.f('ix_segments_replay_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_created_at'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
