"""ORM models: users, replays, segments, tags, votes, reports.

A **segment** is the community-curated unit: it references exactly one replay
plus an inclusive piece-index window `[start_piece, end_piece]` into that
replay's placement track — the same `WindowSelection` shape the trainer uses.

Portable across Postgres/SQLite-style engines by construction (CHAR(36) uuid
strings, plain types, check constraints instead of native enums), though the
deployment is Postgres-only.
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    MetaData,
    SmallInteger,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def new_uuid() -> str:
    return str(uuid.uuid4())


# Deterministic constraint names so autogenerated migrations stay stable and
# ALTERs can target constraints by name on Postgres.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class SmokeNote(Base):
    """Throwaway table proving migrations + test isolation work."""

    __tablename__ = "smoke_notes"

    id: Mapped[int] = mapped_column(primary_key=True)
    note: Mapped[str] = mapped_column(String(200))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class User(Base):
    """An account on this service (Discord OAuth lands here later)."""

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    username: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    # Discord identity (nullable until OAuth is wired; upserted by Discord id).
    discord_id: Mapped[str | None] = mapped_column(
        String(32), unique=True, nullable=True
    )
    avatar_url: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # Moderation rights (report queue, hide/remove segments). No self-serve
    # path: set via ops (UPDATE users SET is_admin = true ...).
    is_admin: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Replay(Base):
    """An ingested solo .ttr: metadata row + pointer into object storage.

    Deduped by content hash — the bytes live once at replays/<hash>.ttr in the
    bucket. `player_username`/`player_userid` identify who *played* (from the
    file); `uploader_id` is the account that submitted it.
    """

    __tablename__ = "replays"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    file_hash: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    storage_key: Mapped[str] = mapped_column(String(128))
    size_bytes: Mapped[int] = mapped_column(Integer)
    filename: Mapped[str] = mapped_column(String(255))
    player_username: Mapped[str] = mapped_column(String(64), index=True)
    player_userid: Mapped[str | None] = mapped_column(String(64), nullable=True)
    uploader_id: Mapped[str | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    gamemode: Mapped[str] = mapped_column(String(32), index=True)
    seed: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    bagtype: Mapped[str | None] = mapped_column(String(32), nullable=True)
    frames: Mapped[int] = mapped_column(Integer)
    pps: Mapped[float | None] = mapped_column(Float, nullable=True)
    apm: Mapped[float | None] = mapped_column(Float, nullable=True)
    vsscore: Mapped[float | None] = mapped_column(Float, nullable=True)
    piece_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Curated play-style label ("downstack", "4wide", …); not derivable from
    # the file, set by curation. Filterable.
    style: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    # Whether the engine can replay this file (bag allowlist + standard board).
    # Zenith parses but is stored with reconstructable = False.
    reconstructable: Mapped[bool] = mapped_column(Boolean)
    reconstructable_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    uploader: Mapped[User | None] = relationship()
    segments: Mapped[list["Segment"]] = relationship(
        back_populates="replay", cascade="all, delete-orphan"
    )

    @property
    def uploader_username(self) -> str | None:
        return self.uploader.username if self.uploader else None


class Segment(Base):
    """A curated window into one replay: pieces [start_piece, end_piece]."""

    __tablename__ = "segments"
    __table_args__ = (
        CheckConstraint("start_piece >= 0", name="start_nonneg"),
        CheckConstraint("end_piece >= start_piece", name="window_ordered"),
        CheckConstraint(
            "difficulty IS NULL OR (difficulty >= 1 AND difficulty <= 5)",
            name="difficulty_range",
        ),
        CheckConstraint(
            "status IN ('pending', 'published', 'removed')", name="status_known"
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    replay_id: Mapped[str] = mapped_column(ForeignKey("replays.id"), index=True)
    author_id: Mapped[str | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    start_piece: Mapped[int] = mapped_column(Integer)
    end_piece: Mapped[int] = mapped_column(Integer)
    title: Mapped[str] = mapped_column(String(120))
    description: Mapped[str] = mapped_column(Text, default="")
    # 1 (easy) .. 5 (brutal); null = unrated.
    difficulty: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    thumbnail_key: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # Author-computed practice stats over the window (board metrics, piece and
    # spin/clear counts). Stored as submitted — UNVERIFIED until a moderator or
    # a server-side reconstruction confirms them (the `verified` flag).
    hints: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    ups: Mapped[int] = mapped_column(Integer, default=0)
    downs: Mapped[int] = mapped_column(Integer, default=0)
    # Denormalized Wilson score lower bound over (ups, downs), recomputed on
    # every vote change; sort=top orders by it. Lower-bound (not ratio) so a
    # 20-up segment outranks a single lucky upvote.
    score: Mapped[float] = mapped_column(Float, default=0.0, index=True)
    verified: Mapped[bool] = mapped_column(Boolean, default=False)
    status: Mapped[str] = mapped_column(String(16), default="published")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )

    replay: Mapped[Replay] = relationship(back_populates="segments")
    author: Mapped[User | None] = relationship()
    tags: Mapped[list["Tag"]] = relationship(secondary="segment_tags")

    @property
    def author_username(self) -> str | None:
        return self.author.username if self.author else None

    @property
    def tag_slugs(self) -> list[str]:
        return sorted(t.slug for t in self.tags)


class Tag(Base):
    """Vocabulary entry: seeded (opener/skill) or user-created free tags (custom)."""

    __tablename__ = "tags"
    __table_args__ = (
        CheckConstraint(
            "category IN ('opener', 'skill', 'custom')", name="category_known"
        ),
    )

    slug: Mapped[str] = mapped_column(String(48), primary_key=True)
    label: Mapped[str] = mapped_column(String(64))
    category: Mapped[str] = mapped_column(String(16))


class SegmentTag(Base):
    __tablename__ = "segment_tags"

    segment_id: Mapped[str] = mapped_column(
        ForeignKey("segments.id"), primary_key=True
    )
    tag_slug: Mapped[str] = mapped_column(
        ForeignKey("tags.slug"), primary_key=True, index=True
    )


class Vote(Base):
    """One up/down vote per user per segment."""

    __tablename__ = "votes"
    __table_args__ = (CheckConstraint("value IN (-1, 1)", name="value_updown"),)

    segment_id: Mapped[str] = mapped_column(
        ForeignKey("segments.id"), primary_key=True
    )
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id"), primary_key=True)
    value: Mapped[int] = mapped_column(SmallInteger)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Report(Base):
    """A user-submitted report against exactly one segment OR one replay."""

    __tablename__ = "reports"
    __table_args__ = (
        CheckConstraint(
            "(segment_id IS NULL) != (replay_id IS NULL)", name="one_target"
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)
    segment_id: Mapped[str | None] = mapped_column(
        ForeignKey("segments.id"), nullable=True, index=True
    )
    replay_id: Mapped[str | None] = mapped_column(
        ForeignKey("replays.id"), nullable=True, index=True
    )
    reporter_id: Mapped[str | None] = mapped_column(
        ForeignKey("users.id"), nullable=True
    )
    reason: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    segment: Mapped[Segment | None] = relationship()
    replay: Mapped[Replay | None] = relationship()
    reporter: Mapped[User | None] = relationship()

    @property
    def reporter_username(self) -> str | None:
        return self.reporter.username if self.reporter else None
